name: Release

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      overwrite:
        description: "Overwrite output even if it doesn't seem outdated? Boolean. Default: false"
        required: true
        default: 'false'


jobs:
  build:
    name: Reaelse index indexorum
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Upload dictionaryIndices to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dictionaryIndices.md
        asset_name: dictionaryIndices.md
        tag: "current"
        overwrite: true
        body: "dictionaryIndices latest"
